### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by Lotarque** [senbox-org/s1tbx#29]
mvn clean install -Dmaven.test.skip=true

Failed to execute goal on project snap-gpf: Could not resolve dependencies for project org.esa.snap:snap-gpf:nbm:6.0.0-SNAPSHOT: Failure to find org.esa.snap:snap-core:jar:tests:6.0.0-SNAPSHOT in http://nexus.senbox.net/nexus/content/repositories/public/ was cached in the local repository

**Comment by lveci** [comment]
Have you built snap-engine? You'll need to mvn clean install on snap-engine at least once so this tests module gets installed. After that you may skip tests.

**Comment by Lotarque** [comment]
This error occurs on the first attempt. It tries to find
snap-gpf:nbm:6.0.0-SNAPSHOT in
http://nexus.senbox.net/nexus/content/repositories/public without success.



Em 15 de mar de 2017 12:23, "Luis Veci" <notifications@github.com> escreveu:

**Comment by Lotarque** [comment]
Running org.esa.snap.core.dataop.downloadable.TestFTPDownloader
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 129.362 sec <<< FAILURE! - in org.esa.snap.core.dataop.downloadable.TestFTPDownloader
testConnect(org.esa.snap.core.dataop.downloadable.TestFTPDownloader)  Time elapsed: 129.362 sec  <<< ERROR!
java.net.ConnectException: Connection timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:182)
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:203)
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:296)
	at org.esa.snap.core.dataop.downloadable.FtpDownloader.connect(FtpDownloader.java:62)
	at org.esa.snap.core.dataop.downloadable.FtpDownloader.<init>(FtpDownloader.java:57)
	at org.esa.snap.core.dataop.downloadable.FtpDownloader.<init>(FtpDownloader.java:50)
	at org.esa.snap.core.dataop.downloadable.TestFTPDownloader.testConnect(TestFTPDownloader.java:38)

**Comment by grousel** [comment]
Hello, thank you for the report.  We are now tracking issues in JIRA, the new ID is https://senbox.atlassian.net/browse/SITBX-608
