### ISSUE TITLE
Reader problem after last update

### ISSUE THREAD

**Issue by MarineROGER** [senbox-org/s1tbx#45]
I did the updates yesterday and since then I can't open any product (raw of processed). How can I fix this ? 

java.lang.NoClassDefFoundError: org/jdom/input/DOMBuilder
	at org.esa.snap.core.dataio.dimap.DimapProductReader.readDom(DimapProductReader.java:251)
	at org.esa.snap.core.dataio.dimap.DimapProductReader.processProduct(DimapProductReader.java:136)
	at org.esa.snap.core.dataio.dimap.DimapProductReader.readProductNodesImpl(DimapProductReader.java:117)
	at org.esa.snap.core.dataio.AbstractProductReader.readProductNodes(AbstractProductReader.java:169)
	at org.esa.snap.core.dataio.ProductIO.readProduct(ProductIO.java:161)
	at org.esa.snap.rcp.actions.file.ReadProductOperation.run(ReadProductOperation.java:51)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)

**Comment by marpet** [comment]
I have also the latest updates installed and it works on my system.
Maybe something went wrong during the update. 
You can try to delete the update information. It is located on Windows
at `%appdata%/SNAP`. Simply type this in the file explorer.
Then delete the directories:
**_modules
update
update_tracking_**
On Unix systems go to 
`<user_directory>\.snap` and delete the _**system**_ folder.
Then you need to install the updates again.
If this does not help you can try to reinstall SNAP and do the update again.

**Comment by MarineROGER** [comment]
Thank you. I deleted the system folder and it is working again.
